spring:
  application:
    name: taskmanager
  datasource:
    url: jdbc:postgresql://localhost:5434/taskmanager
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true